jh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name='index'),
    path('web-development-services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
    path('sw.js', (TemplateView.as_view(template_name="sw.js", content_type="application/javascript")), name="service_worker")
]

main/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    sender_name = models.CharField(max_length=50)
    sender_email = models.EmailField()
    message = models.TextField()
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (self.sender_email)

main/forms.py
from django import forms

class MessageForm(forms.Form):
    sender_name = forms.CharField(label='Name ', max_length=50)
    sender_email = forms.EmailField(label='Email address ')
    message = forms.CharField(label='Your message ', widget=forms.Textarea(attrs={'class': 'materialize-textarea'}))

main/views.py
import os
import ssl
from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
# from django.core.mail import send_mail

import sendgrid
from sendgrid.helpers.mail import *

from .forms import MessageForm
from .models import Message

#ssl._create_default_https_context = ssl._create_unverified_context

# Create your views here.

def index(request):
    return render(request, 'main/index.html')

def services(request):
    return render(request, 'main/services.html')

def contact(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            m = Message(
                sender_name=data['sender_name'],
                sender_email=data['sender_email'],
                message=data['message'],
                time=datetime.now()
            )
            if m.sender_name != '' \
            and m.sender_email != '' \
            and m.message != '':
                m.save()

                # Email arguments
                subject = 'Message on Holmes Web Development from %s' % (m.sender_name)

                intro = (
                '''Sent: %s

From: %s

Email: %s \n\n
                ''' % (m.time, m.sender_name, m.sender_email))

                content = m.message

                # try:
                #     send_mail(
                #         subject,
                #         (intro + content),
                #         'jar3dh0lm3s@gmail.com',
                #         ['jared@colgro.com'],
                #         fail_silently=False
                # )
                # except:
                #     return render(request, 'main/contact-failed.html', context = { 'form' : form })
                # return render(request, 'main/contact-thanks.html', context = { 'form' : form })

                sg = sendgrid.SendGridAPIClient(apikey=os.environ.get('SENDGRID_API_KEY'))
                from_email = Email('jared@colgro.com')
                to_email = Email('jared@colgro.com')
                email_subject = subject
                email_content = Content('text/plain', intro + content)
                mail = Mail(from_email, email_subject, to_email, email_content)
                response = sg.client.mail.send.post(request_body=mail.get())

                if response.status_code == 202:
                    return render(request, 'main/contact-thanks.html', context = { 'form' : form })
                else:
                    return render(request, 'main/contact-thanks.html', context = { 'form' : form })

    else: form = MessageForm()

    return render(request, 'main/contact.html', context = { 'form' : form })

main/templates/main/base.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-123404483-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-123404483-1');
  </script>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block meta-description %}
    <meta name="description" content="Holmes Web Development offers various web design and development services aimed at accelerating business growth online.">
  {% endblock %}
  <meta name="theme-color" content="#007677">
  {% load static %}
  <link rel="icon" type="image/png" href="{% static 'main/src/images/favicon.png' %}">
  <link href="https://fonts.googleapis.com/css?family=Raleway:300,400" rel="stylesheet">
  <link rel="manifest" href="{% static 'main/src/manifest/manifest.json'%}">
  {% block extra-links %}
  {% endblock %}
  <title>{% block title %}Holmes Web Development | Website and Web Application Development{% endblock%}</title>
</head>
{% render_bundle 'styles' %}
<body class="font-1 light-grey charcoal-text">
  <div id="app">
    <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper light-grey">
          <h1><a class="brand-logo left font-2" href="{% url 'main:index' %}"> <img class="logo" src="{% static 'main/src/images/logo.png' %}" alt=""> Holmes <div class="subheading">Web <br />Development</div></a></h1>
          <ul class="right">
            <li><a href="#" class="sidenav-trigger teal-text text-accent-2" data-target="slidenav"><img src='{% static 'main/src/icons/icon-menu.png' %}' class="icon"></a></li>
          </ul>
          <ul class="right nav-mobile hide-on-med-and-down">
            {% block nav-which-active %}
              <li><a href="{% url 'main:index' %}" class="nav-active charcoal-text">Home</a></li>
              <li><a href="{% url 'main:services' %}" class="charcoal-text">Services</a></li>
              <li><a href="{% url 'main:contact' %}" class="charcoal-text">Contact & Pricing</a></li>
            {% endblock %}
          </ul>
        </div>
      </nav>
    </div>
    <ul class="sidenav" id="slidenav">
      <li><a href="{% url 'main:index' %}" class="waves-effect waves-blue">Home</a></li>
      <li><a href="{% url 'main:services' %}" class="waves-effect waves-blue">Services</a></li>
      <li><a href="{% url 'main:contact' %}" class="waves-effect waves-blue">Contact</a></li>
    </ul>


    <div class="page-header">
      {% block page-header %}
      {% endblock %}
    </div>


    {% block cover-image %}
    {% endblock %}

    <main class="main container row">
      {% block main %}
      <div class="cont-block" id="cont-block-1">
        <h2 class="font-2 bright-blue-text">Overview</h2>
        <div class="cont-paragraph" id="cont-paragraph-1">
          <p>I'm a freelance web developer based in Johannesburg, South Africa. My main interest lies in front-end web design, which allows me to create clean and charming websites aimed at communicating the personality of the business behind the website.</p>

          <p>If you need a website to showcase all that you have to offer through the world's most powerful and flexible medium, you have come to the right place. For a more detailed breakdown of what I do, <a href="{% url 'main:services' %}">visit the services page</a>.</p>
        </div>
      </div>

      <div class="cont-block" id="cont-block-2">
        <h2 class="font-2 bright-blue-text">Need a Website?</h2>
        <div class="cont-paragraph" id="cont-paragraph-2">
          <p>I'd love to help showcase you to the world. To get started, you can find my contact details or send me a message <a href="{% url 'main:contact' %}">here</a>.</p>
        </div>
      </div>
      {% endblock %}
    </main>

    <footer class="page-footer mid-grey">
      <div class="row valign-wrapper charcoal-text">
        <div class="col s7">
          <ul>
            <h2><li><a href="{% url 'main:index' %}">Home</a></li></h2>
            <h2><li><a href="{% url 'main:services' %}">Web development services</a></li></h2>
            <h2><li><a href="{% url 'main:contact' %}">Contact & Pricing</a></li></h2>
            <br>
            <h2><li>Our partner: <a href="http://www.colgro.com/index.html" class="link-colgro" target="_blank">ColGro</a></li>
            </ul></h2>
          </ul>
        </div>
        <div class="col s5 right-align">
          <ul>
            {% block extra-footer %}
            {% endblock %}
            <li><span id="copy"></span></li>
          </ul>
        </div>
      </div>
    </footer>
  </div>

  {% render_bundle 'index' %}
  {% render_bundle 'externals' %}
  {% block extra-scripts %}
  {% endblock %}
</body>
</html>

main/templates/main/contact-failed.html
{% extends "main/contact.html" %}
{% block extra-scripts %}
  {% load static %}
  <script src="{% static 'main/src/scripts/toast_contact_failed.js' %}" charset="utf-8"></script>
{% endblock %}

main/templates/main/contact-thanks.html
{% extends "main/contact.html" %}
{% block extra-scripts %}
  {% load static %}
  <script src="{% static 'main/src/scripts/toast_contact_thanks.js' %}" charset="utf-8"></script>
{% endblock %}

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta-description %}
  <meta name="description" content="Holmes Web Development offers various web design and development services aimed at accelerating business growth online.">
{% endblock %}

{% block title %}Contact Details and Pricing | Holmes Web Development{% endblock %}

{% block nav-which-active %}
  <li><a href="{% url 'main:index' %}">Home</a></li>
  <li><a href="{% url 'main:services' %}">Services</a></li>
  <li><a href="{% url 'main:contact' %}" class="nav-active">Contact & Pricing</a></li>
{% endblock %}

{% block page-header %}
  <h1 class="font-2">Contact Details & Pricing</h1>
{% endblock %}

{% block cover-image %}
{% endblock %}

{% block main %}
<div class="cont-block">
  <h2 class="font-2 bright-blue-text">Pricing</h2>
  <div class="cont-paragraph" id="cont-paragraph-1">
    <p>The web development aspects listed in the <a href="{% url 'main:services' %}">services page</a> vary in complexity and price. Since each project is unique, quotes will be calculated after establishing your specific requirements. In order to gauge your requirements, an initial meeting can be held to discuss your requirements, free of charge. This can be done remotely or face-to-face.</p>
  </div>
</div>

<div class="cont-block">
  <h2 class="font-2 bright-blue-text">Send a Message</h2>
  <div class="cont-paragraph" id="cont-paragraph-1">
    <p>If you have any comments, questions or requests feel free to let me know here.</p>
  </div>
  <form class="new-message" action="" method="post">
    {% csrf_token %}
      <div class="form-area input-field">
        <img src="{% static 'main/src/icons/icon-name.png' %}" alt="Name" class="contact-icon prefix">
        <label for="id_name">Name </label>
        {{ form.sender_name }}
      </div>
      <div class="form-area input-field">
        <img src="{% static 'main/src/icons/icon-email.png' %}" alt="Email" class="contact-icon prefix">
        <label for="id_email">Email address </label>
        {{ form.sender_email }}
      </div>
      <div class="form-area input-field">
        <img src="{% static 'main/src/icons/icon-pencil.png' %}" alt="Message" class="contact-icon prefix">
        <label for="id_message">Your message </label>
        {{ form.message }}
      </div>
      <div class="right-align">
        <button type="submit" name="" class="btn waves-effect waves-blue bright-blue" id="btn-submit">Send &nbsp;<img src="{% static 'main/src/icons/icon-send.png' %}" alt="Message" class="send-icon"></button>
      </div>
  </form>
</div>

<div class="cont-block" id="cont-block-1">
  <h2 class="font-2 bright-blue-text">Contact Me</h2>
  <div class="cont-paragraph" id="cont-paragraph-1">
    <p>E-mail: <a href="mailto: jared@colgro.com">jared@colgro.com</a></p>
  </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% block cover-image %}
<div class="cover-image">
  <img id="cover" width="100%" alt="Holmes Web Development" src="{% static 'main/src/images/background.jpeg' %}">
  <div class="slogan">
    <h2 id="slogan-1" class="animated"><a href="{% url 'main:services' %}" class="charcoal-text"><img src="{% static 'main/src/icons/icon-coding.png' %}" alt="web design" class="slogan-icon">&nbsp; <span id="timeout">[[ timeout(0) ]]</span> High-quality, bespoke website design</a></h2>
  </div>
</div>
<div class="blender"></div>
{% endblock %}
{% block extra-footer %}
<li><a href="https://icons8.com">Icon pack by Icons8</a></li>
{% endblock %}
{% block extra-scripts %}

<script type="text/javascript">
var text = [
    "<a href='{% url 'main:services' %}' class='charcoal-text'><img src='{% static 'main/src/icons/icon-coding.png' %}' alt='web design' class='slogan-icon'>&nbsp; High-quality, bespoke website design</a>",

    "<a href='{% url 'main:services' %}' class='charcoal-text'><img src='{% static 'main/src/icons/icon-ux.png' %}' alt='UX and UI' class='slogan-icon'>&nbsp; Attractive and intuitive UI and UX design</a>",

    "<a href='{% url 'main:services' %}' class='charcoal-text'><img src='{% static 'main/src/icons/icon-database.png' %}' alt='Web application design' class='slogan-icon'>&nbsp; Robust, performant web application development</a>",

    "<a href='{% url 'main:services' %}' class='charcoal-text'><img src='{% static 'main/src/icons/icon-search.png' %}' alt='SEO' class='slogan-icon'>&nbsp; Search engine optimization for maximized exposure</a>",
  ];
</script>
{% render_bundle 'animate' %}
{% endblock %}

main/templates/main/message.html
<h1>New Message</h1>
<br>
<form class="new-message" action="" method="post">
  {% csrf_token %}
    <div class="sec1" style="margin: 3em;">
      <label for="id_name">Name: </label>
      {{ form.sender_name }}
    </div>
    <div class="sec1" style="margin: 3em;">
      <label for="id_email">Email: </label>
      {{ form.sender_email }}
    </div>
    <div class="sec1" style="margin: 3em;">
      <label for="id_message" style="position: relative; bottom: 7em;">Your message: </label>
      {{ form.message }}
    </div>
    <input type="submit" name="" value="Submit" id="sub">
</form>

main/templates/main/services.html
{% extends 'main/base.html' %}
{% load static %}

{% block meta-description %}
  <meta name="description" content="Holmes Web Development services: web development, UX & UI, web application development, progressive web apps, logo's and branding and SEO (search engine optimisation).">
{% endblock %}

{% block title %}Web Design and Development Services | Holmes Web Development{% endblock %}

{% block nav-which-active %}
  <li><a href="{% url 'main:index' %}">Home</a></li>
  <li><a href="{% url 'main:services' %}" class="nav-active">Services</a></li>
  <li><a href="{% url 'main:contact' %}">Contact & Pricing</a></li>
{% endblock %}

{% block page-header %}
  <h1 class="font-2">Web Development Services</h1>
{% endblock %}

{% block cover-image %}
{% endblock %}

{% block main %}
  <div class="cont-block" id="cont-block-1">
      <h2 class="font-2 bright-blue-text">Services</h2>
      <div class="cont-paragraph" id="cont-paragraph-1">
        <p>I offer various services designed to cater to the needs of businesses or individuals in need of websites.</p>
        <ul class="collapsible z-depth-0">
          <li class="active">
            <h2 class="font-2 collapsible-header bright-blue-text"><img src="{% static 'main/src/icons/icon-coding.png' %}" alt="web design" class="services-icon"> Web Design and Development</h2>
              <div class="collapsible-body"><p>The most fundamental service is basic web design and development, ideal for brochure sites or portfolio-based websites, crucial for any business to showcase itself effectively.</p></div>
          </li>
          <li>
            <h2 class="font-2 collapsible-header bright-blue-text"><img src="{% static 'main/src/icons/icon-ux.png' %}" alt="UX and UI" class="services-icon"> UX & UI</h2>
              <div class="collapsible-body"><p>Linked closely with web development, user interface and user experience design involve creating a website that follows proper design practices in order to create an enjoyable and intuitive experience for the user. This includes aspects such as visual design, responsive design and typography.</p></div>
          </li>
          <li>
            <h2 class="font-2 collapsible-header bright-blue-text"><img src="{% static 'main/src/icons/icon-database.png' %}" alt='Web application design' class="services-icon"> Web Applications</h2>
              <div class="collapsible-body"><p>The web application is a more advanced type of website which offers the user a more interactive and "app-like" experience. Web applications generally rely on the retrieval of information from a database. This allows for a more customizable and powerful experience.</p></div>
          </li>
          <li>
            <h2 class="font-2 collapsible-header bright-blue-text"><img src="{% static 'main/src/icons/icon-smartphone.png' %}" alt="Progressive web app" class="services-icon"> Progressive Web Apps</h2>
              <div class="collapsible-body"><p>Progessive web apps essentially websites configured to be offer some native application functionality such as offline functionality and push notifications. Progressive web apps are can be 'installed', similarly to traditional applications on Android phones.

              If you want to test this out, and you're viewing this page on an Android phone using Chrome or Firefox, tap the browser's menu button and select "Add to home screen".</p></div>
          </li>
          <li>
            <h2 class="font-2 collapsible-header bright-blue-text"><img src="{% static 'main/src/icons/icon-blog.png' %}" alt="CMS" class="services-icon"> Content Management Systems</h2>
              <div class="collapsible-body"><p>Content management systems  provide a user-friendly interface that allows users, owners and administrators to easily create displayable content for a website. Most blogs use content management systems, as content creators can manage their content without any web development knowledge.</p></div>
          </li>
          <li>
            <h2 class="font-2 collapsible-header bright-blue-text"><img src="{% static 'main/src/icons/icon-graph.png' %}" alt="D3.js" class="services-icon"> Data Visualisation</h2>
              <div class="collapsible-body"><p>Data visualisation allows data to be displayed in unique and customizable ways, making data more significantly more interesting than plain text. For examples of interesting data visualisations, visit the <a href="https://github.com/d3/d3/wiki/Gallery">D3 gallery</a> </p>.</div>
          </li>
          <li>
            <h2 class="font-2 collapsible-header bright-blue-text"><img src="{% static 'main/src/icons/icon-eye.png' %}" alt="logo design" class="services-icon"> Logo Design</h2>
              <div class="collapsible-body"><p>Eye-catching and expressive logos are important for the establishment of a business's brand image. Following visual design and logo design guidelines, I provide logo designs with the purpose of creating a memorable brand image.</p></div>
          </li>
          <li>
            <h2 class="font-2 collapsible-header bright-blue-text"><img src="{% static 'main/src/icons/icon-search.png' %}" alt='SEO' class="services-icon"> Search Engine Optimisation (SEO)</h2>
              <div class="collapsible-body"><p>Search engine optimisation is the process of optimising a website through multiple adjustments for the purpose of ranking a website higher in search engine results. This generates more traffic from users, as the website is made significantly more available to the public.</p></div>
          </li>
        </ul>
      </div>
    </div>

  </div>
{% endblock %}

{% block extra-footer %}
<li><a href="https://icons8.com">Icon pack by Icons8</a></li>
{% endblock %}